export const DEPARTMENTS = [
  'General Medicine',
  'Cardiology',
  'Orthopedics',
  'Pediatrics',
  'Dermatology',
  'Neurology',
  'Emergency',
];

export const DOCTORS = [
  { id: 'doc-1', name: 'Dr. Sarah Jenkins', department: 'Cardiology', status: 'active', patientsSeen: 14, avgConsultTime: 18 },
  { id: 'doc-2', name: 'Dr. Marcus Webb', department: 'Cardiology', status: 'active', patientsSeen: 12, avgConsultTime: 22 },
  { id: 'doc-3', name: 'Dr. Emily Chen', department: 'Pediatrics', status: 'active', patientsSeen: 20, avgConsultTime: 12 },
  { id: 'doc-4', name: 'Dr. Michael Scott', department: 'General Medicine', status: 'active', patientsSeen: 25, avgConsultTime: 10 },
  { id: 'doc-5', name: 'Dr. Olivia Martinez', department: 'General Medicine', status: 'active', patientsSeen: 22, avgConsultTime: 14 },
  { id: 'doc-6', name: 'Dr. James Wilson', department: 'Orthopedics', status: 'active', patientsSeen: 8, avgConsultTime: 25 },
  { id: 'doc-7', name: 'Dr. Lisa Cuddy', department: 'Dermatology', status: 'active', patientsSeen: 18, avgConsultTime: 15 },
  { id: 'doc-8', name: 'Dr. Robert Chase', department: 'Emergency', status: 'active', patientsSeen: 30, avgConsultTime: 8 },
  { id: 'doc-9', name: 'Dr. Allison Cameron', department: 'Neurology', status: 'active', patientsSeen: 5, avgConsultTime: 35 },
  { id: 'doc-10', name: 'Dr. Gregory House', department: 'General Medicine', status: 'break', patientsSeen: 2, avgConsultTime: 45 },
];

// Helper to generate a random time today
const getRandomTimeToday = (hoursAgoStart, hoursAgoEnd) => {
  const now = new Date();
  const past = new Date(now.getTime() - (Math.random() * (hoursAgoStart - hoursAgoEnd) + hoursAgoEnd) * 3600000);
  return past.toISOString();
};

export const INITIAL_PATIENTS = [
  {
    id: 'pat-1001',
    tokenNumber: 'A-001',
    name: 'John Doe',
    age: 45,
    gender: 'Male',
    phone: '555-0101',
    symptoms: 'Mild chest pain, shortness of breath',
    visitType: 'new',
    department: 'Cardiology',
    appointmentType: 'walk-in',
    isEmergency: false,
    arrivalTime: getRandomTimeToday(2, 1),
    status: 'waiting', // waiting, in-consultation, completed, missed
    assignedDoctorId: 'doc-1',
    priorityScore: 0, // Calculated by AI
    priorityLevel: 'Medium', // Assigned by AI
    aiExplanation: '',
    estimatedWaitTime: 0,
  },
  {
    id: 'pat-1002',
    tokenNumber: 'B-001',
    name: 'Jane Smith',
    age: 28,
    gender: 'Female',
    phone: '555-0102',
    symptoms: 'Routine checkup for blood pressure',
    visitType: 'follow-up',
    department: 'General Medicine',
    appointmentType: 'booked',
    isEmergency: false,
    arrivalTime: getRandomTimeToday(1.5, 0.5),
    status: 'in-consultation',
    assignedDoctorId: 'doc-4',
    priorityScore: 0,
    priorityLevel: 'Low',
    aiExplanation: '',
    estimatedWaitTime: 0,
  },
  {
    id: 'pat-1003',
    tokenNumber: 'E-001',
    name: 'Robert Johnson',
    age: 62,
    gender: 'Male',
    phone: '555-0103',
    symptoms: 'Severe bleeding from arm laceration',
    visitType: 'emergency',
    department: 'Emergency',
    appointmentType: 'walk-in',
    isEmergency: true,
    arrivalTime: getRandomTimeToday(0.5, 0),
    status: 'waiting',
    assignedDoctorId: 'doc-8',
    priorityScore: 0,
    priorityLevel: 'Critical',
    aiExplanation: '',
    estimatedWaitTime: 0,
  },
  {
    id: 'pat-1004',
    tokenNumber: 'C-001',
    name: 'Alice Williams',
    age: 8,
    gender: 'Female',
    phone: '555-0104',
    symptoms: 'High fever, ongoing for 3 days',
    visitType: 'new',
    department: 'Pediatrics',
    appointmentType: 'walk-in',
    isEmergency: false,
    arrivalTime: getRandomTimeToday(3, 2),
    status: 'waiting',
    assignedDoctorId: 'doc-3',
    priorityScore: 0,
    priorityLevel: 'High',
    aiExplanation: '',
    estimatedWaitTime: 0,
  },
  {
    id: 'pat-1005',
    tokenNumber: 'D-001',
    name: 'Michael Brown',
    age: 50,
    gender: 'Male',
    phone: '555-0105',
    symptoms: 'Knee pain after fall',
    visitType: 'new',
    department: 'Orthopedics',
    appointmentType: 'walk-in',
    isEmergency: false,
    arrivalTime: getRandomTimeToday(4, 3),
    status: 'waiting',
    assignedDoctorId: 'doc-6',
    priorityScore: 0,
    priorityLevel: 'Medium',
    aiExplanation: '',
    estimatedWaitTime: 0,
  },
  {
    id: 'pat-1006',
    tokenNumber: 'A-002',
    name: 'Emily Davis',
    age: 70,
    gender: 'Female',
    phone: '555-0106',
    symptoms: 'Heart palpitations',
    visitType: 'follow-up',
    department: 'Cardiology',
    appointmentType: 'booked',
    isEmergency: false,
    arrivalTime: getRandomTimeToday(1, 0),
    status: 'waiting',
    assignedDoctorId: 'doc-2',
    priorityScore: 0,
    priorityLevel: 'Medium',
    aiExplanation: '',
    estimatedWaitTime: 0,
  },
  // Add more to reach ~10 patients for initial state to keep it manageable but visible
  {
    id: 'pat-1007',
    tokenNumber: 'F-001',
    name: 'William Garcia',
    age: 35,
    gender: 'Male',
    phone: '555-0107',
    symptoms: 'Persistent headache and blurred vision',
    visitType: 'new',
    department: 'Neurology',
    appointmentType: 'walk-in',
    isEmergency: false,
    arrivalTime: getRandomTimeToday(2.5, 1.5),
    status: 'waiting',
    assignedDoctorId: 'doc-9',
    priorityScore: 0,
    priorityLevel: 'Medium',
    aiExplanation: '',
    estimatedWaitTime: 0,
  },
  {
    id: 'pat-1008',
    tokenNumber: 'B-002',
    name: 'Sophia Martinez',
    age: 22,
    gender: 'Female',
    phone: '555-0108',
    symptoms: 'Sore throat and cough',
    visitType: 'new',
    department: 'General Medicine',
    appointmentType: 'walk-in',
    isEmergency: false,
    arrivalTime: getRandomTimeToday(0.5, 0.1),
    status: 'waiting',
    assignedDoctorId: 'doc-5',
    priorityScore: 0,
    priorityLevel: 'Low',
    aiExplanation: '',
    estimatedWaitTime: 0,
  },
  {
    id: 'pat-1009',
    tokenNumber: 'G-001',
    name: 'David Rodriguez',
    age: 40,
    gender: 'Male',
    phone: '555-0109',
    symptoms: 'Skin rash on arms',
    visitType: 'follow-up',
    department: 'Dermatology',
    appointmentType: 'booked',
    isEmergency: false,
    arrivalTime: getRandomTimeToday(1.2, 0.8),
    status: 'waiting',
    assignedDoctorId: 'doc-7',
    priorityScore: 0,
    priorityLevel: 'Low',
    aiExplanation: '',
    estimatedWaitTime: 0,
  },
  {
    id: 'pat-1010',
    tokenNumber: 'C-002',
    name: 'Isabella Hernandez',
    age: 4,
    gender: 'Female',
    phone: '555-0110',
    symptoms: 'Ear infection, crying constantly',
    visitType: 'new',
    department: 'Pediatrics',
    appointmentType: 'walk-in',
    isEmergency: false,
    arrivalTime: getRandomTimeToday(0.2, 0),
    status: 'waiting',
    assignedDoctorId: 'doc-3',
    priorityScore: 0,
    priorityLevel: 'High',
    aiExplanation: '',
    estimatedWaitTime: 0,
  }
];
